[package]
name = "ferret"
description = "Doom-compatible game engine"
version = "0.1.0"
authors = ["Rua <ruawhitepaw@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0"
arrayvec = {version = "0.5", features = ["serde"]}
bitflags = "1.2"
byteorder = "1.3"
clap = "2.33"
colored = "2.0"
crossbeam-channel = "0.5.0"
derivative = "2.1"
downcast-rs = "1.2"
fnv = "1.0"
lazy_static = "1.4"
legion = {git = "https://github.com/rua/legion", default-features = false, features = ["extended-tuple-impls", "serialize"], branch = "serde-rearrange"}
log = {version = "0.4.8", features = ["std"]}
nalgebra = {version = "0.24.0", features = ["serde-serialize"]}
num-traits = "0.2.11"
rand = "0.8"
rand_pcg = {version = "0.3", features = ["serde1"]}
regex = "1.3"
relative-path = "1.3.2"
rmp-serde = {version = "0.15.1", features = ["serde128"]}
rodio = {version = "0.13.0", default-features = false}
scoped-tls-hkt = "0.1.2"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
shrev = "1.1"
smallvec = "1.4"
vulkano = "0.20"
vulkano-shaders = "0.20"
vulkano-win = "0.20"
winit = "0.24"

[profile.dev]
opt-level = 1

[profile.release]
incremental = true
lto = true
