[package]
name = "ferret"
description = "Doom-compatible game engine"
version = "0.1.0"
authors = ["Rua <ruawhitepaw@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0"
arrayvec = "0.5.1"
bitflags = "1.2"
byteorder = "1.3"
clap = "2.33"
colored = "2.0"
crossbeam-channel = "0.4.2"
derivative = "2.1"
downcast-rs = "1.2"
fnv = "1.0"
lazy_static = "1.4"
legion = {git = "https://github.com/amethyst/legion", default-features = false, features = ["extended-tuple-impls"]}
log = {version = "0.4.8", features = ["std"]}
nalgebra = "0.22.0"
num-traits = "0.2.11"
rand = "0.7"
rand_pcg = "0.2.1"
regex = "1.3"
relative-path = "1.3.2"
rodio = {version = "0.12.0", default-features = false}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
shrev = "1.1"
smallvec = "1.4"
vulkano = {git = "https://github.com/vulkano-rs/vulkano"}
vulkano-shaders = "0.19"
vulkano-win = {git = "https://github.com/vulkano-rs/vulkano"}
winit = {version = "0.22.2"}

[profile.dev]
opt-level = 1

[profile.release]
incremental = true
lto = true
