[package]
name = "ferret"
version = "0.1.0"
authors = ["Rua <ruawhitepaw@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
alto = "3.0.3"
byteorder = "1.2.7"
colored = "1.6.1"
downcast-rs = "1.0.3"
lazy_static = "1.2.0"
log = {version = "0.4.6", features = ["release_max_level_info"]}
nalgebra = "0.16.12"
net2 = "0.2.33"
regex = "1.1.0"
sdl2 = {git = "https://github.com/Rust-SDL2/rust-sdl2/", features = ["mixer"]}
vulkano = "0.11.1"
vulkano-shaders = "0.11.1"
weak-table = "0.2.3"
