[package]
name = "ferret"
description = "Doom-compatible game engine"
version = "0.1.0"
authors = ["Rua <ruawhitepaw@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0"
arrayvec = "0.5.1"
bitflags = "1.2"
byteorder = "1.3"
clap = "2.33"
colored = "1.9"
crossbeam-channel = "0.4.2"
derivative = "2.1"
fnv = "1.0"
lazy_static = "1.4"
log = {version = "0.4.8", features = ["std"]}
nalgebra = "0.20.0"
num-traits = "0.2.10"
rand = "0.7"
rand_pcg = "0.2.1"
regex = "1.3"
rodio = {version = "0.11.0", default-features = false}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
shrev = "1.1"
smallvec = "1.4"
specs = "0.16.1"
specs-derive = "0.4.1"
vulkano = "0.18"
vulkano-shaders = "0.18"
vulkano-win = "0.18"
winit = {version = "0.22.1", features = ["serde"]}

[profile.release]
lto = true
