[package]
name = "ferret"
version = "0.1.0"
authors = ["Rua <ruawhitepaw@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
bitflags = "1.2"
byteorder = "1.3"
colored = "1.9"
derivative = "1.0"
lazy_static = "1.4"
log = {version = "0.4.8", features = ["release_max_level_info"]}
nalgebra = "0.19.0"
num-traits = "0.2.10"
rand = "0.7"
rand_pcg = "0.2.1"
regex = "1.3"
rodio = "0.10.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
specs = "0.16.1"
specs-derive = "0.4.1"
vulkano = "0.17"
vulkano-shaders = "0.17"
vulkano-win = "0.17"
winit = {version = "0.21.0", features = ["serde"]}
