use specs::world::EntityBuilder;
use std::collections::HashMap;

lazy_static! {
	pub(crate) static ref ENTITIES: HashMap<&'static str, (fn(EntityBuilder) -> EntityBuilder)> = {
		let mut m: HashMap<&'static str, (fn(EntityBuilder) -> EntityBuilder)> = HashMap::new();
		m.insert("SPAWN1", |b| b);
		m.insert("SPAWN2", |b| b);
		m.insert("SPAWN3", |b| b);
		m.insert("SPAWN4", |b| b);
		m.insert("DMSPAWN", |b| b);
		m.insert("PLAYER", |b| b);
		m.insert("POSSESSED", |b| b);
		m.insert("SHOTGUY", |b| b);
		m.insert("VILE", |b| b);
		m.insert("FIRE", |b| b);
		m.insert("UNDEAD", |b| b);
		m.insert("TRACER", |b| b);
		m.insert("SMOKE", |b| b);
		m.insert("FATSO", |b| b);
		m.insert("FATSHOT", |b| b);
		m.insert("CHAINGUY", |b| b);
		m.insert("TROOP", |b| b);
		m.insert("SERGEANT", |b| b);
		m.insert("SHADOWS", |b| b);
		m.insert("HEAD", |b| b);
		m.insert("BRUISER", |b| b);
		m.insert("BRUISERSHOT", |b| b);
		m.insert("KNIGHT", |b| b);
		m.insert("SKULL", |b| b);
		m.insert("SPIDER", |b| b);
		m.insert("BABY", |b| b);
		m.insert("CYBORG", |b| b);
		m.insert("PAIN", |b| b);
		m.insert("WOLFSS", |b| b);
		m.insert("KEEN", |b| b);
		m.insert("BOSSBRAIN", |b| b);
		m.insert("BOSSSPIT", |b| b);
		m.insert("BOSSTARGET", |b| b);
		m.insert("SPAWNSHOT", |b| b);
		m.insert("SPAWNFIRE", |b| b);
		m.insert("BARREL", |b| b);
		m.insert("TROOPSHOT", |b| b);
		m.insert("HEADSHOT", |b| b);
		m.insert("ROCKET", |b| b);
		m.insert("PLASMA", |b| b);
		m.insert("BFG", |b| b);
		m.insert("ARACHPLAZ", |b| b);
		m.insert("PUFF", |b| b);
		m.insert("BLOOD", |b| b);
		m.insert("TFOG", |b| b);
		m.insert("IFOG", |b| b);
		m.insert("TELEPORTMAN", |b| b);
		m.insert("EXTRABFG", |b| b);
		m.insert("MISC0", |b| b);
		m.insert("MISC1", |b| b);
		m.insert("MISC2", |b| b);
		m.insert("MISC3", |b| b);
		m.insert("MISC4", |b| b);
		m.insert("MISC5", |b| b);
		m.insert("MISC6", |b| b);
		m.insert("MISC7", |b| b);
		m.insert("MISC8", |b| b);
		m.insert("MISC9", |b| b);
		m.insert("MISC10", |b| b);
		m.insert("MISC11", |b| b);
		m.insert("MISC12", |b| b);
		m.insert("INV", |b| b);
		m.insert("MISC13", |b| b);
		m.insert("INS", |b| b);
		m.insert("MISC14", |b| b);
		m.insert("MISC15", |b| b);
		m.insert("MISC16", |b| b);
		m.insert("MEGA", |b| b);
		m.insert("CLIP", |b| b);
		m.insert("MISC17", |b| b);
		m.insert("MISC18", |b| b);
		m.insert("MISC19", |b| b);
		m.insert("MISC20", |b| b);
		m.insert("MISC21", |b| b);
		m.insert("MISC22", |b| b);
		m.insert("MISC23", |b| b);
		m.insert("MISC24", |b| b);
		m.insert("MISC25", |b| b);
		m.insert("CHAINGUN", |b| b);
		m.insert("MISC26", |b| b);
		m.insert("MISC27", |b| b);
		m.insert("MISC28", |b| b);
		m.insert("SHOTGUN", |b| b);
		m.insert("SUPERSHOTGUN", |b| b);
		m.insert("MISC29", |b| b);
		m.insert("MISC30", |b| b);
		m.insert("MISC31", |b| b);
		m.insert("MISC32", |b| b);
		m.insert("MISC33", |b| b);
		m.insert("MISC34", |b| b);
		m.insert("MISC35", |b| b);
		m.insert("MISC36", |b| b);
		m.insert("MISC37", |b| b);
		m.insert("MISC38", |b| b);
		m.insert("MISC39", |b| b);
		m.insert("MISC40", |b| b);
		m.insert("MISC41", |b| b);
		m.insert("MISC42", |b| b);
		m.insert("MISC43", |b| b);
		m.insert("MISC44", |b| b);
		m.insert("MISC45", |b| b);
		m.insert("MISC46", |b| b);
		m.insert("MISC47", |b| b);
		m.insert("MISC48", |b| b);
		m.insert("MISC49", |b| b);
		m.insert("MISC50", |b| b);
		m.insert("MISC51", |b| b);
		m.insert("MISC52", |b| b);
		m.insert("MISC53", |b| b);
		m.insert("MISC54", |b| b);
		m.insert("MISC55", |b| b);
		m.insert("MISC56", |b| b);
		m.insert("MISC57", |b| b);
		m.insert("MISC58", |b| b);
		m.insert("MISC59", |b| b);
		m.insert("MISC60", |b| b);
		m.insert("MISC61", |b| b);
		m.insert("MISC62", |b| b);
		m.insert("MISC63", |b| b);
		m.insert("MISC64", |b| b);
		m.insert("MISC65", |b| b);
		m.insert("MISC66", |b| b);
		m.insert("MISC67", |b| b);
		m.insert("MISC68", |b| b);
		m.insert("MISC69", |b| b);
		m.insert("MISC70", |b| b);
		m.insert("MISC71", |b| b);
		m.insert("MISC72", |b| b);
		m.insert("MISC73", |b| b);
		m.insert("MISC74", |b| b);
		m.insert("MISC75", |b| b);
		m.insert("MISC76", |b| b);
		m.insert("MISC77", |b| b);
		m.insert("MISC78", |b| b);
		m.insert("MISC79", |b| b);
		m.insert("MISC80", |b| b);
		m.insert("MISC81", |b| b);
		m.insert("MISC82", |b| b);
		m.insert("MISC83", |b| b);
		m.insert("MISC84", |b| b);
		m.insert("MISC85", |b| b);
		m.insert("MISC86", |b| b);
		m
	};
	pub(crate) static ref DOOMEDNUMS: HashMap<u16, &'static str> = {
		let mut m: HashMap<u16, &'static str> = HashMap::new();
		m.insert(1, "SPAWN1");
		m.insert(2, "SPAWN2");
		m.insert(3, "SPAWN3");
		m.insert(4, "SPAWN4");
		m.insert(11, "DMSPAWN");
		m.insert(3004, "POSSESSED");
		m.insert(9, "SHOTGUY");
		m.insert(64, "VILE");
		m.insert(66, "UNDEAD");
		m.insert(67, "FATSO");
		m.insert(65, "CHAINGUY");
		m.insert(3001, "TROOP");
		m.insert(3002, "SERGEANT");
		m.insert(58, "SHADOWS");
		m.insert(3005, "HEAD");
		m.insert(3003, "BRUISER");
		m.insert(69, "KNIGHT");
		m.insert(3006, "SKULL");
		m.insert(7, "SPIDER");
		m.insert(68, "BABY");
		m.insert(16, "CYBORG");
		m.insert(71, "PAIN");
		m.insert(84, "WOLFSS");
		m.insert(72, "KEEN");
		m.insert(88, "BOSSBRAIN");
		m.insert(89, "BOSSSPIT");
		m.insert(87, "BOSSTARGET");
		m.insert(2035, "BARREL");
		m.insert(14, "TELEPORTMAN");
		m.insert(2018, "MISC0");
		m.insert(2019, "MISC1");
		m.insert(2014, "MISC2");
		m.insert(2015, "MISC3");
		m.insert(5, "MISC4");
		m.insert(13, "MISC5");
		m.insert(6, "MISC6");
		m.insert(39, "MISC7");
		m.insert(38, "MISC8");
		m.insert(40, "MISC9");
		m.insert(2011, "MISC10");
		m.insert(2012, "MISC11");
		m.insert(2013, "MISC12");
		m.insert(2022, "INV");
		m.insert(2023, "MISC13");
		m.insert(2024, "INS");
		m.insert(2025, "MISC14");
		m.insert(2026, "MISC15");
		m.insert(2045, "MISC16");
		m.insert(83, "MEGA");
		m.insert(2007, "CLIP");
		m.insert(2048, "MISC17");
		m.insert(2010, "MISC18");
		m.insert(2046, "MISC19");
		m.insert(2047, "MISC20");
		m.insert(17, "MISC21");
		m.insert(2008, "MISC22");
		m.insert(2049, "MISC23");
		m.insert(8, "MISC24");
		m.insert(2006, "MISC25");
		m.insert(2002, "CHAINGUN");
		m.insert(2005, "MISC26");
		m.insert(2003, "MISC27");
		m.insert(2004, "MISC28");
		m.insert(2001, "SHOTGUN");
		m.insert(82, "SUPERSHOTGUN");
		m.insert(85, "MISC29");
		m.insert(86, "MISC30");
		m.insert(2028, "MISC31");
		m.insert(30, "MISC32");
		m.insert(31, "MISC33");
		m.insert(32, "MISC34");
		m.insert(33, "MISC35");
		m.insert(37, "MISC36");
		m.insert(36, "MISC37");
		m.insert(41, "MISC38");
		m.insert(42, "MISC39");
		m.insert(43, "MISC40");
		m.insert(44, "MISC41");
		m.insert(45, "MISC42");
		m.insert(46, "MISC43");
		m.insert(55, "MISC44");
		m.insert(56, "MISC45");
		m.insert(57, "MISC46");
		m.insert(47, "MISC47");
		m.insert(48, "MISC48");
		m.insert(34, "MISC49");
		m.insert(35, "MISC50");
		m.insert(49, "MISC51");
		m.insert(50, "MISC52");
		m.insert(51, "MISC53");
		m.insert(52, "MISC54");
		m.insert(53, "MISC55");
		m.insert(59, "MISC56");
		m.insert(60, "MISC57");
		m.insert(61, "MISC58");
		m.insert(62, "MISC59");
		m.insert(63, "MISC60");
		m.insert(22, "MISC61");
		m.insert(15, "MISC62");
		m.insert(18, "MISC63");
		m.insert(21, "MISC64");
		m.insert(23, "MISC65");
		m.insert(20, "MISC66");
		m.insert(19, "MISC67");
		m.insert(10, "MISC68");
		m.insert(12, "MISC69");
		m.insert(28, "MISC70");
		m.insert(24, "MISC71");
		m.insert(27, "MISC72");
		m.insert(29, "MISC73");
		m.insert(25, "MISC74");
		m.insert(26, "MISC75");
		m.insert(54, "MISC76");
		m.insert(70, "MISC77");
		m.insert(73, "MISC78");
		m.insert(74, "MISC79");
		m.insert(75, "MISC80");
		m.insert(76, "MISC81");
		m.insert(77, "MISC82");
		m.insert(78, "MISC83");
		m.insert(79, "MISC84");
		m.insert(80, "MISC85");
		m.insert(81, "MISC86");
		m
	};
}
